services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./ex00/d04:/var/www/symfony
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - ./ex00/d04:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
